name: Release
on:
  push:
    tags:
        - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build to jar
        run: gradle build

      - name: Parse Changelog
        id: parse_changelog
        shell: bash
        run: |
          CHANGELOG=$(awk '/^# Release [0-9]+\.[0-9]+\.[0-9]+/{p=1; print; next} p&&/^# Release [0-9]+\.[0-9]+\.[0-9]+|^___/{p=0} p' CHANGELOG.md)
          
          delimiter="$(openssl rand -hex 8)"
          {
            echo "changelog<<${delimiter}"
            echo "$CHANGELOG"
            echo "${delimiter}"
          } >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.parse_changelog.outputs.changelog }}
          files: build/libs/SkyForce-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}